#!/usr/bin/expect -f
#
#
set passname [lindex $argv 0]
set pass1 [lindex $argv 1]
set pass2 [lindex $argv 2]
set mod [lindex $argv 3]

if { "$mod" == "" } {
spawn pass insert $passname
} else {
spawn pass $mod insert $passname
}
expect "?nter*"
send -- "$pass1\r"
send -- "$pass2\r"
send -- "\r"

# done
expect eof
