#!/bin/sh

drive="$(lsblk -rpo "name,type,size,mountpoint" | grep -v /dev/nvme | grep 'part\|rom' | awk '$4==""{printf "%s (%s)\n",$1,$3}')"
chosen="$(echo "$drive" | dmenu -i -p "Mount which drive?")" || exit 1
chosen="$(echo "$chosen" | awk '{print $1}')"
sudo mount "$chosen" /media/mina
alacritty -e lf /media/mina


